spring:
  datasource:
    url: jdbc:mysql://db:3306/store_api?createDatabaseIfNotExist=true
    username: admin
    password: admin
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path: /api/v1/docs
  api-docs:
    path: /api/v1/api-docs

websiteUrl: http://localhost:4242 # placeholder value

